name: Sergey Maskalik's Blog
url: http://blog.maskalik.com
author: Sergey Maskalik
markdown: redcarpet
pygments: false
permalink: pretty
paginate: 3
paginate_path: ":num"
exclude: ['./assets','publish.bat']
include: ['sitemap.xml']
encoding: UTF-8
assets:
  sources:
  - assets/js
  - assets/css
  js_compressor: uglifier
  css_compressor: sass